// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://djdtmhvaihdvvpfjtvvc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRqZHRtaHZhaWhkdnZwZmp0dnZjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNDMzNjgsImV4cCI6MjA1ODcxOTM2OH0.aPnVO0nnAMfCu-VE95ARR_DcHknnrvWmRigqPrnIMWg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);